# Generated by Django 3.0.7 on 2020-06-12 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('ma_nhaCungCap', models.AutoField(primary_key=True, serialize=False)),
                ('ten_nhaCungCap', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nhà Cung Cấp',
                'verbose_name_plural': 'Nhà Cung Cấp',
                'db_table': 'NHACUNGCAP',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_NhanVien', models.AutoField(primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=50)),
                ('DiaChi', models.CharField(max_length=50)),
                ('SoDT', models.CharField(max_length=11)),
                ('CMND', models.CharField(max_length=11)),
                ('GioiTinh', models.CharField(choices=[(1, 'Nam'), (2, 'Nữ'), (3, 'Khác...')], max_length=5)),
                ('ma_nhaCungCap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NhaCungCap')),
            ],
            options={
                'verbose_name': 'Nhân Viên',
                'verbose_name_plural': 'Nhân Viên',
                'db_table': 'NHANVIEN',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NhaXuatBan',
            fields=[
                ('ma_NhaXuatBan', models.AutoField(primary_key=True, serialize=False)),
                ('ten_NhaXuatBan', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nhà Xuất Bản',
                'verbose_name_plural': 'Nhà Xuất Bản',
                'db_table': 'NHAXUATBAN',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TacGia',
            fields=[
                ('ma_TacGia', models.AutoField(primary_key=True, serialize=False)),
                ('ten_Tacgia', models.CharField(max_length=50)),
                ('ghiChu', models.CharField(max_length=255, null='true')),
            ],
            options={
                'verbose_name': 'Tác Giả',
                'verbose_name_plural': 'Tác Giả',
                'db_table': 'TACGIA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('ma_TheLoai', models.AutoField(primary_key=True, serialize=False)),
                ('ten_theLoai', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Thể Loại',
                'verbose_name_plural': 'Thể Loại',
                'db_table': 'THELOAI',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('ma_SinhVien', models.CharField(max_length=50, primary_key='true', serialize=False)),
                ('ten_SinhVien', models.CharField(max_length=50)),
                ('gioiTinh', models.CharField(choices=[(1, 'Nam'), (2, 'Nữ'), (3, 'Khác...')], max_length=5)),
                ('lop', models.CharField(max_length=10)),
                ('NamSinh', models.DateField()),
                ('diaChi', models.CharField(max_length=100)),
                ('khoa', models.CharField(max_length=20)),
                ('nhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NhanVien')),
            ],
            options={
                'verbose_name': 'Sinh Viên',
                'verbose_name_plural': 'Sinh Viên',
                'db_table': 'SINHVIEN',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('ma_Sach', models.AutoField(primary_key=True, serialize=False)),
                ('ten_Sach', models.CharField(max_length=50)),
                ('soLuong', models.IntegerField()),
                ('namXuatBan', models.IntegerField(default=2020)),
                ('anh', models.ImageField(max_length=255, upload_to='')),
                ('loaiSach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TheLoai')),
                ('nhaXuatBan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NhaXuatBan')),
                ('tacGia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TacGia')),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Sách',
                'db_table': 'BOOK',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhieuYeuCau',
            fields=[
                ('ma_PhieuYeuCau', models.AutoField(primary_key=True, serialize=False)),
                ('ten_phieuYeuCau', models.CharField(max_length=50)),
                ('soLuong', models.IntegerField()),
                ('TenSach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Sach')),
                ('nhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NhanVien')),
            ],
            options={
                'verbose_name': 'Phiếu Yêu Cầu',
                'verbose_name_plural': 'Phiếu Yêu Cầu',
                'db_table': 'PHIEUYEUCAU',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BaoCao',
            fields=[
                ('ma_BaoCao', models.AutoField(primary_key=True, serialize=False)),
                ('ngay', models.DateTimeField()),
                ('ma_nhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NhanVien')),
            ],
            options={
                'verbose_name': 'Báo Cáo',
                'verbose_name_plural': 'Báo Cáo',
                'db_table': 'BAOCAO',
                'managed': True,
            },
        ),
    ]
