# Generated by Django 3.0.7 on 2020-06-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSach',
            fields=[
                ('ma_TopSach', models.AutoField(primary_key=True, serialize=False)),
                ('sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Sach')),
            ],
            options={
                'verbose_name': 'Top Sách',
                'verbose_name_plural': 'Top Sách',
                'db_table': 'TopSach',
                'managed': True,
            },
        ),
    ]
