# Generated by Django 3.0.7 on 2020-06-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='GioiTinh',
            field=models.IntegerField(choices=[(1, 'Nam'), (2, 'Nữ'), (3, 'Khác...')]),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='gioiTinh',
            field=models.IntegerField(choices=[(1, 'Nam'), (2, 'Nữ'), (3, 'Khác...')]),
        ),
    ]
