# Generated by Django 3.0.7 on 2020-06-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_topsach'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieuyeucau',
            name='trang_thai',
            field=models.CharField(choices=[(1, 'Đang xử lý'), (2, 'Chưa trả'), (3, 'Đã trả')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
