# Generated by Django 3.0.7 on 2020-06-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_phieuyeucau_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieuyeucau',
            name='trang_thai',
            field=models.CharField(choices=[(1, 'Đang xử lý'), (2, 'Chưa trả'), (3, 'Đã trả')], default=1, max_length=10),
        ),
    ]
