# Generated by Django 3.0.7 on 2020-06-14 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200614_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phieuyeucau',
            name='nhanVien',
        ),
    ]
