# Generated by Django 3.0.7 on 2020-06-14 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_phieuyeucau_nhanvien'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieuyeucau',
            name='sinhvien',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.SinhVien'),
            preserve_default=False,
        ),
    ]
